# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import lend.models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0004_auto_20160807_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lender',
            name='price_d',
        ),
        migrations.AlterField(
            model_name='lender',
            name='calendar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lender',
            name='price_h',
            field=models.CharField(help_text='30분 이용 가격 (숫자로만 입력)', max_length=10, validators=[lend.models.price_validator]),
        ),
    ]
