# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0005_auto_20160807_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lender',
            name='tags',
        ),
        migrations.AddField(
            model_name='lender',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lend.Tag'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(choices=[('1', '세그웨이'), ('2', '전동 퀵보드')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[('1', '서울대입구'), ('2', '서울대'), ('3', '녹두'), ('4', '낙성대')], max_length=20),
        ),
    ]
